/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jvm_internals_ArrayListNative */

#ifndef _Included_com_jvm_internals_ArrayListNative
#define _Included_com_jvm_internals_ArrayListNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jvm_internals_ArrayListNative
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jvm_internals_ArrayListNative_size
  (JNIEnv *, jobject);

/*
 * Class:     com_jvm_internals_ArrayListNative
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jvm_internals_ArrayListNative_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_jvm_internals_ArrayListNative
 * Method:    add
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jvm_internals_ArrayListNative_add
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jvm_internals_ArrayListNative
 * Method:    remove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jvm_internals_ArrayListNative_remove
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jvm_internals_ArrayListNative
 * Method:    get
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jvm_internals_ArrayListNative_get
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jvm_internals_ArrayListNative
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jvm_internals_ArrayListNative_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
